version: "3.9"

services:
  db:
    network_mode: host
    image: nginx-geo
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites:/var/www/
      - ./db:/usr/lib/nginx-geo/db/
      - ./conf/sites:/etc/nginx/conf.d/
